<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>TODO: Get nesting to work correctly. 
	Currently, the links are only picked up outside of paragraphs.</string>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>markdown</string>
		<string>mdown</string>
		<string>markdn</string>
		<string>md</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~W</string>
	<key>name</key>
	<string>Wiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#delimited</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#camelcase</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>camelcase</key>
		<dict>
			<key>match</key>
			<string>[A-Z][a-z]+([A-Z][a-z]*)+</string>
			<key>name</key>
			<string>markup.other.pagename.camelcase</string>
		</dict>
		<key>delimited</key>
		<dict>
			<key>begin</key>
			<string>\[\[</string>
			<key>contentName</key>
			<string>markup.other.pagename.delimited</string>
			<key>end</key>
			<string>\]\]</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown.wiki</string>
	<key>uuid</key>
	<string>F861513D-753A-4D79-8679-4EE3D034F5A8</string>
</dict>
</plist>
